config/routes.rb
Devstreak::Application.routes.draw do
  resources :submissions, :only => [:new, :create]

  match '/details' => 'home#details'
  match '/team' => 'home#team'
  match '/contact' => 'home#contact'
  match '/apply' => 'submissions#new'

  match '/participate' => 'home#participate'

  root :to => 'home#index'
end

app/models/submission.rb
class Submission < ActiveRecord::Base; end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'application'
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
  def details; end
  def team; end
  def contact; end

  def participate; end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def new; end

  def create
    @submission = Submission.new(params[:submission])
    @submission.save!
    render :nothing => true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    classes = [*controller.controller_path.split('/'),
               controller.controller_name,
               controller.action_name]
    classes.uniq.compact.join(' ')
  end
end

app/views/home/contact.html.erb
<h2>Frequently Asked Questions</h2>
<div class="well">
  <p>If you can't find your answer in the frequently asked questions below, or if you just want to say hi, send us an email and you'll get a prompt reply!</p>
  <a href="mailto:contact@codestreak.com" target="_blank" class="btn btn-info inline">contact@codestreak.com</a>
</div>
<br />

<h4>I can't make it to San Francisco. Is there a way to attend the program online?</h4>
<blockquote>
  <p>At this time we're only offering the program onsite. A big part of what we do is one-on-one mentoring, and that's a lot more effective if done in person.</p>
</blockquote>

<h4>Does the program cover room and board?</h4>
<blockquote>
  <p>You'll have to provide for your own housing and dining. Two great resources for finding apartments in SF are <a href="https://www.padmapper.com/" target="_blank">PadMapper</a> and <a href="http://www.housingmaps.com/" target="_blank">HousingMaps</a>.</p>
</blockquote>

<h4>Do I need to bring a computer?</h4>
<blockquote>
  <p>We'll provide Mac Minis and large-screen displays for you to use while in the program. If you'd like to use a different development environment, or if you're just more comfortable with your own setup, you're completely welcome to bring that.</p>
</blockquote>

<h4>Where will the program be held?</h4>
<blockquote>
  <p>The program will be held in downtown SoMa in San Francisco, and we're currently evaluating options for the perfect classroom space. A primary consideration in choosing the right space is proximity to BART and Muni, so rest assured that using public transit will be simple.</p>
</blockquote>

<h4>Will I be pair-programming all the time?</h4>
<blockquote>
  <p>Probably. We think pairing is an excellent way to get up to speed and to make sure that you're sticking to good style while you're learning. In the first part of the program we'll be rotating pairs every day, and once you settle into groups you can self-organize and choose your partners.</p>
</blockquote>

<h4>How many students will be accepted?</h4>
<blockquote>
  <p>We're keeping our options open on this for right now, but we're envisioning class sizes between 18 and 24. Depending on the number of instructors/mentors we have, we may run multiple classes in parallel. Regardless of class size, the plan is to have one full-time instructor per six students to ensure that everyone gets a large amount of individual attention.</p>
</blockquote>

<h4>What if I already have some experience in Computer Science?</h4>
<blockquote>
  <p>While codeStreak is primary targeted to individuals without much technical experience, we feel that anyone excited to learn Ruby on Rails will benefit greatly from the program. Having a CS background will improve your experience more than anything, as you'll be able to pick up the best practices and patterns a bit quicker, and you'll develop an even more impressive capstone project.</p>
</blockquote>

<h4>What if it isn't what I expected?</h4>
<blockquote>
  <p>We're confident that you'll love the program and will want to see it through to the end. However, if something comes up and you'd like to withdraw during the first week, we'll refund $4,000 of your tuition.</p>
</blockquote>

<h4>I'd like to be an instructor / mentor / guest speaker / demo day employer. Is there any info for me?</h4>
<blockquote>
  <p>We'd love to talk with you - head on over to the <a href="<%= participate_path %>">participate page</a> for some details on what we're looking for.</p>
</blockquote>

<p class="well">
 Ready to kickstart your career as a Ruby on Rails developer? <a href="<%= apply_path %>" class="btn btn-primary" style="margin-left: 6px">Apply Now!</a>
</p>

app/views/home/details.html.erb
<h3>Program Details</h3>
<dl>
  <dt>General</dt>
  <div class="alert">
  codeStreak has been postponed for the foreseeable future due to a lack of interested students.  Feel free to email team@codestreak.com with any questions or comments.  Thanks!
  </div>

  <dd>codeStreak is a 6-week Ruby on Rails program intended for individuals with little or no technical background. From 9am-5pm each day, you'll be joining us in our space in downtown San Francisco, and taking a practical approach to learning software development. Through a combination of instruction, mentoring, and exploration, you'll train up to the level of a good, junior software engineer. The program is extremely pragmatic - while you will learn the basics of computer science theory, the focus is on how to quickly build working applications.</dd>
  <br />
  <dt>Schedule</dt>
  <dd>
    <div class="row">
      <!--<p class="span4">For those of you with plans of learning how to code in the coming year, remember that Monday, March 4th is the program's first day of class. The first three weeks of the program will be instruction and hands-on coding exercises. During the second three weeks, you'll be working in small groups to build a demo application to show off to potential employers. The focus for these weeks is individual instruction - we'll really step up the mentoring and focus on any knowledge gaps or areas of particular interest.</p>
  <img src="<%= image_path('calendar.png') %>" class="span7" style="border-radius: 16px;" /></dd>
  --><br />
  <dt>Curriculum</dt>
  <dd>
    The curriculum we have lined up is practical and packed with hands-on activities. The list of subject areas and technologies below, while definitely not exhaustive, will give you a good idea of what we have in store for you. It's a lot to cover in six weeks, and with some dedication we're confident we can work through it together!
    <div class="row">
      <ul class="span3 offset1">
        <li>Ruby on Rails</li>
        <li>RSpec</li>
        <li>View templating (ERB)</li>
        <li>HTML/CSS (Twitter Bootstrap)</li>
        <li>JavaScript (jQuery)</li>
        <li>Data structures</li>
        <li>Data modeling</li>
      </ul>
      <ul class="span3">
        <li>Variables and expressions</li>
        <li>Flow/control statements</li>
        <li>Class and instance methods</li>
        <li>String manipulation</li>
        <li>Working with files</li>
        <li>Metaprogramming</li>
        <li>Algorithm complexity</li>
      </ul>
      <ul class="span3">
        <li>Source control management (git)</li>
        <li>Test-driven development</li>
        <li>Agile methodology</li>
        <li>Extreme programming</li>
        <li>Infrastructure basics (Heroku/AWS)</li>
        <li>Interview tips and tricks</li>
        <li>Mock interviews</li>
      </ul>
    </div>
  </dd>
  <br />
  <dt>Community</dt>
  <dd>You know how there's all those stories about people making great lifelong friends at summer camp? Well, you might not find your soulmate at codeStreak, but you'll definitely find supportive people that you'll love to work with. The community aspect of the program is extremely important to us - in addition to being proven to enhance learning efficacy, it's just great motivation to be working in a supportive environment. Two of the most frequent reasons people fall behind in education (of any sort) are due to a lack of support and a lack of accountability. Our team and the other students in the codeStreak community will be there with you every step of the way to help you succeed!</dd>
  <br />
  <dt>Demo Day</dt>
  <dd>The final day of the program is an opportunity to show off your new skills to potential employers. We're bringing in hiring managers from Bay-area companies, big and small, and they're excited to meet you! You'll get to present the application you're been working on for the past six weeks to them, and it should be impressive enough to score you a sweet job as a full-time developer.</dd>
  <br />
  <a name="tuition"></a>
  <dt>Program Tuition</dt>
  <dd>Tuition for the program is $6,000 - it's a small investment for your future and your new career.</dd>
</dl>

<p class="well">
 Decided that you'd like to be a developer? <a href="<%= apply_path %>" class="btn btn-primary" style="margin-left: 6px">Apply Now!</a>
</p>

app/views/home/index.html.erb
<%= javascript_include_tag "home/parallax.js" %>
<div id="headline" class="row">
  <div class="span10">
    <h1><b>Learn Ruby on Rails in 6 action-packed weeks.</b></h1>
  <div class="alert">
  codeStreak has been postponed for the foreseeable future due to a lack of interested students.  Feel free to email team@codestreak.com with any questions or comments.  Thanks!
  </div>
  <p>Learn to code in 2013 as part of our inaugural cohort! Our curriculum will provide students of any background with the ability to work as a full-time software developer and the skills to build their own product.</p>
  </div>
  <div class="span2 bounce-in">
    <img src="<%= image_path('home/ruby_on_rails.png') %>" />
  </div>
</div>

</div>
<div id="banner">
  <div class="container">
    <div id="banner-graphics">
      <div id="banner-macbook"></div>
    </div>
    <ul id="banner-icons">
      <li>
      <a id="icon-community" class="has-icon" href="#community">
        <h4>Make connections</h4>
        <p>Meet like-minded individuals at our San Francisco office.</p>
      </a>
      </li>
      <li>
      <a id="icon-mentoring" class="has-icon" href="#mentoring">
        <h4>Gain experience</h4>
        <p>Learn from veteran developers who are excited to share their experience.</p>
      </a>
      </li>
      <li>
      <a id="icon-opportunity" class="has-icon" href="#opportunity">
        <h4>Prepare for a new career</h4>
        <p>Work on a portfolio project and interview skills to impress employers and investors.</p>
      </a>
      </li>
    </ul>
  </div>
</div>
<div class="container">

<div class="containing">
  <div class="content row_b">
    <div id="community" class="row_b">
      <div class="column c_fit">
                <div class="text">
                  <h2>Join a world-class learning community!</h2>
                  <p>We will host the next cohort of great developers at our office in downtown San Francisco.  We encourage working in code as much as possible - and challenging students to build projects as a group!</p>
                  <p><a class="btn btn-large btn-inverse row-b-cta" href="<%= details_path %>">Learn more »</a></p>
                  <div id="screenshots-timers" class="screenshots">
                    <span class="open"></span>
                  </div>
                </div>
              </div>
      <div class="column c_fit last">
                <div id="cloud-holder">
                  <img id="cloud-1" src="<%= image_path('home/cloud_1.png')%>"></img>
                  <img id="bridge" src="<%= image_path('home/bridge2.png')%>"></img>
                  <img id="cloud-2" src="<%= image_path('home/cloud_2.png')%>"></img>
                  <img id="cloud-3" src="<%= image_path('home/cloud_4.png')%>"></img>
                </div>
              </div>
    </div>
    <div id="mentoring" class="row_b">
              <div id="desktop" style="background-position: 0px 50px; background-size: 100%; ">
                <div id="heroku_code"></div>
                <div class="glare"></div>
              </div>
              <div class="text">
                <h2>Evolve as a developer with industry mentorship!</h2>
                <p>We have put together a team of excited, experienced developers to assist you in your quest to working as a competent coder.  We will be having guest lectures, a carousel of teachers, and hands-on assistance in coding exercises.</p>
                <p><a class="btn btn-large btn-inverse row-b-cta" href="<%= team_path %>">Meet the team »</a></p>
                <div class="screenshots">
                </div>
              </div>
    </div>
    <div id="opportunity" class="row_b">
              <div class="text">
                <h2>Take control of career opportunities in Silicon Valley!</h2>
                <p>The average salary for a Ruby on Rails developer in SF is <a href="http://www.indeed.com/salary/q-Ruby-On-Rails-Developer-l-San-Francisco,-CA.html" target="blank"> over $100k</a>, according to indeed™. Our program will help you to impress potential employers with the projects you'll be working on!</p>
                <p><a class="btn btn-large btn-inverse row-b-cta" href="<%= contact_path %>">Any questions? »</a></p>
                <div class="screenshots">
                  </div>
              </div>
              <div id="opportunity-tooltip" style="opacity: 0; -webkit-transform: scale(0); "><p>November 2012</p><small>$117,000 national avg.</small></div>
              <img id="opportunity-graph" src="<%= image_path('home/graph.png') %>" />
    </div>
    <div id="press">
      <span class="cronos">Companies Hiring Ruby on Rails Developers</span>
      <div>
        <img class="pressLogo" src="<%= image_path('/assets/home/twitter_logo.jpeg') %>" />
        <img class="pressLogo" src="<%= image_path('/assets/home/linkedin_logo.jpg') %>" />
        <img class="pressLogo" src="<%= image_path('/assets/home/groupon_logo.jpeg') %>" />
        <img class="pressLogo" src="<%= image_path('/assets/home/cisco_logo.png') %>" />
        <img class="pressLogo" src="<%= image_path('/assets/home/jp_morgan_logo.gif') %>" />
        <img class="pressLogo" src="<%= image_path('/assets/home/thoughtworks_logo.png') %>" />
        <img class="pressLogo" src="<%= image_path('/assets/home/scribd_logo.png') %>" />
        <img class="pressLogo" src="<%= image_path('/assets/home/amazon_logo.png') %>" />
        <img class="pressLogo" src="<%= image_path('/assets/home/ibm_logo.jpg') %>" />
        <img class="pressLogo" src="<%= image_path('/assets/home/yahoo_logo.jpg') %>" />
      </div>
    </div>
    <div id="apply_now" class="row">
      <div class="ruby-wrapper span2 offset1">
        <img class="ruby-image" src="/assets/home/ruby.png">
        <img class="glimmer-1" src="/assets/home/glimmer.png">
        <img class="glimmer-2" src="/assets/home/glimmer2.png">
      </div>
      <div class="cta-apply span8" style="margin-left: 40px;">
        <h2 id="apply-hook">Ready to start building stunning web applications?</h2>
        <a class="btn btn-large btn-primary" href="<%= apply_path %>">Apply
          Now! </a>
        <span id="offramp"><span style="margin-left:15px;"> or <a href="<%= details_path %>">Learn More </a></span></span>
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {
    $("#banner-icons").on("click", "a", function() {
      scrollTo($(this).attr("href"));
      return false;
    });
  });
</script>

app/views/home/participate.html.erb
<h3>Participate</h3>

<p>We're specifically interested in talking to folks about the following roles. If you have a different opportunity in mind, let us know!</p>

<dl>
  <dt>Instructors</dt>
  <dd>The quality of our curriculum is extremely important to us, and a very large part of that comes down to our instructors. If you're an experienced Ruby on Rails developer and enjoy teaching, drop us a line! You'll love working with us - our environment is fantastic, and the competitive pay is a nice bonus as well.</dd>
  <br />
  <dt>Guest speakers</dt>
  <dd>Interested in sharing your knowledge, but don't have the bandwidth to teach full-time? We've left a bit of spare time in our schedule for guest presentations. It's a great way to improve your public speaking skills and to get your name out there, so send us a note if you're interested.</dd>
  <br />
  <dt>Employers</dt>
  <dd>Demo day is an integral part of our program. A large portion of program time is spent working on a capstone project, and our students are really looking forward to interviewing with potential new employers. If you're interested in seeing if our students might be a good fit for your team, RSVP now to reserve your spot at the event!</dd>
</dl>

<div class="well">
  <p>Want to get involved? Email us!</p>
  <a href="mailto:contact@codestreak.com" class="btn btn-info inline" style="margin-left: 6px">contact@codestreak.com</a>
</div>

app/views/home/team.html.erb
<h3>Meet the team!</h3>

<div class="row">
  <img src="<%= image_path('team/justin.jpg') %> " class="span2" style="border: 1px solid black; padding: 4px;" />
  <div class="span4">
    <h4>Justin Pincar</h4>
    <div>
      Justin has been teaching and coding since he was in middle school. He's given brown-bags, led tech talks, delivered lectures, facilitated classes, and even developed and taught full-scale college courses. He's built out many web apps for companies large and small, and is now thrilled to share his experience and knowledge at codeStreak!
      <br /><a href="http://www.linkedin.com/in/justinpincar" target="_blank">View Justin's LinkedIn</a>
    </div>
  </div>

  <img src="<%= image_path('team/kevin.jpg') %> " class="span2" style="border: 1px solid black; padding: 4px;" />
  <div class="span4">
    <h4>Kevin Meehan</h4>
    <div>
      Kevin came to the Bay Area after spending a few years writing software for the government in Washington, D.C. He was attracted by San Francisco's gung-ho startup culture, and has only fallen more in love with it since the move. He is an avid runner who enjoys inquisitively reading books, volunteering for SFCASA, and sipping black coffee.
      <br /><a href="http://www.linkedin.com/pub/kevin-meehan/a/4a6/381" target="_blank">View Kevin's LinkedIn</a>
    </div>
  </div>
</div>
<br />

<div class="row">
  <img src="<%= image_path('team/mike.jpg') %> " class="span2" style="border: 1px solid black; padding: 4px;" />
  <div class="span4">
    <h4>Mike Sample</h4>
    <div>
      Mike sauntered through many walks of life (for instance, running his own coffee shop, hustling on Wall Street, and working as a gas station attendant) before settling into the field that's most important to him: education. With an anecdote for any situation, Mike is one of the world's best storytellers, tying his fantastic experiences to the present.
      <br /><a href="http://www.linkedin.com/pub/mike-sample/1/752/154" target="_blank">View Mike's LinkedIn</a>
    </div>
  </div>

  <img src="<%= image_path('team/chris.jpg') %> " class="span2" style="border: 1px solid black; padding: 4px;" />
  <div class="span4">
    <h4>Chris Kung</h4>
    <div>
      As a Silicon Valley native, it's not surprising that Chris started out by building websites for his dad's company. The exposure provided a natural transition to enter the software industry, where he worked on web/mobile apps with a data analytics focus. Chris is excited for the opportunity to mentor while also pursuing his own ventures.
      <br /><a href="http://www.linkedin.com/profile/view?id=6891911" target="_blank">View Chris's LinkedIn</a>
    </div>
  </div>
</div>
<br />
<p class="well">
Already looked at the <a href="<%= details_path %>">details page</a> and still wondering something? <a href="<%= contact_path %>" class="btn btn-primary" style="margin-left: 6px">Check out the FAQ!</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>codeStreak</title>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="description" content="Learn to code Ruby on Rails applications within weeks in downtown San Francisco with codeStreak"/>
    <meta name="keywords" content="learn, program, tutorial, code, ruby, rails, san francisco, sf, full time, ror, developer, job" />
    <meta property="og:title" content="codeStreak: Learn to code in SF in 6 weeks!" />
    <meta property="og:url" content="http://www.codestreak.com" />
    <meta property="og:image" content="<%=request.protocol + request.host_with_port + image_path('home/ruby_on_rails.png')%>" />
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-34869045-1']);
      _gaq.push(['_trackPageview']);

      (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
       })();
     </script>
     <script type="text/javascript" src="//use.typekit.net/lpk4dad.js"></script>
     <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  </head>
  <body class="<%= body_class %>">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="<%= root_path %>">
            <img src="<%= image_path('sidespin-logo.png') %>" /> codeStreak
          </a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li <%= 'class="active"'.html_safe if body_class.include?("index") %>><a href="<%= root_path %>">Home</a></li>
              <li <%= 'class="active"'.html_safe if body_class.include?("details") %>><a href="<%= details_path %>">Details</a></li>
              <li <%= 'class="active"'.html_safe if body_class.include?("team") %>><a href="<%= team_path %>">Team</a></li>
              <li <%= 'class="active"'.html_safe if body_class.include?("contact") %>><a href="<%= contact_path %>">Contact + FAQ</a></li>
            </ul>
            <a href="<%= apply_path %>" class="btn btn-primary pull-right">Apply Now!</a>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>

      <hr>
      <footer>
      <p>&copy; Tigerlily Labs, Inc. 2012 | <a href="<%= participate_path %>">Participate</a> | <a href="mailto:contact@codestreak.com?subject=Hey%20there%2C%20I%20was%20wondering%20about..." target="_blank">contact@codestreak.com</a></p>
      </footer>
    </div> <!-- /container -->
    <div id="sharrre" data-url="http://www.codeStreak.com" data-title="share"></div>
    <script>
      $('#sharrre').sharrre({
        share: {
          googlePlus: true,
          facebook: true,
          twitter: true
        },
        buttons: {
          googlePlus: {size: 'tall'},
          facebook: {layout: 'box_count'},
          twitter: {count: 'vertical'}
        },
        hover: function(api, options){
          $(api.element).find('.buttons').show();
        },
        hide: function(api, options){
          $(api.element).find('.buttons').hide();
        },
        enableTracking: true
      });
    </script>
    <style>
      #sharrre {
        position: fixed;
        bottom: 20px;
        left: 20px;
        width: 300px;
      }
      .sharrre .box{
        float:left;
      }
      .sharrre .count {
        color:#444444;
        display:block;
        font-size:17px;
        line-height:34px;
        height:34px;
        padding:4px 0;
        position:relative;
        text-align:center;
        text-decoration:none;
        width:50px;
        background-color:#eee;
        -webkit-border-radius:4px;
        -moz-border-radius:4px;
        border-radius:4px;
      }
      .sharrre .share {
        color:#FFFFFF;
        display:block;
        font-size:11px;
        height:16px;
        line-height:16px;
        margin-top:3px;
        padding:0;
        text-align:center;
        text-decoration:none;
        width:50px;
        background-color:#9CCE39;
        -webkit-border-radius:4px;
        -moz-border-radius:4px;
        border-radius:4px;
      }
      .sharrre .buttons {
        display:none;
        position:absolute;
        margin-left:50px;
        z-index:10;
      }
      .sharrre .button {
        float:left;
        max-width:50px;
        margin-left:10px;
      }
    </style>
  </body>
</html>

app/views/submissions/new.html.erb
<h3>Apply to be a part of the inaugural codeStreak cohort!</h3>

<div class="alert">
  codeStreak planning is currently on hold.  We unfortunately do now know when we will hold our next session, but any and all submissions will be considered.
</div>

<%= form_for(:submission, :url => submissions_path, :html => {:id => "submissions_form", :class => 'form-horizontal'}) do |f| %>
  <div class="control-group">
    <label class="control-label" for="inputName">Name</label>
    <div class="controls">
      <input name="submission[name]" type="text" id="inputName" class="span4" placeholder="Name">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Email</label>
    <div class="controls">
      <input name="submission[email]" type="text" id="inputEmail" class="span4" placeholder="Email">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEssaySelf">Essay</label>
    <div class="controls controls-row">
      <textarea name="submission[essay_self]" id="inputEssaySelf" class="span4" rows="10" placeholder="Response here..."></textarea><span class="span4 inline">Tell us a little bit about yourself. Why would you like to learn to be a developer, and why is the codeStreak program important to you?</span>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEssayTreehouse">Essay</label>
    <div class="controls controls-row">
      <textarea name="submission[essay_treehouse]" id="inputEssayTreehouse" class="span4" rows="10" placeholder="Response here..."></textarea><span class="span4 inline">Imagine there's a tree in your backyard (if you don't have a backyard, you should probably imagine that too), and that you would like to build a treehouse. Write a short essay (maximum 100 words) on how you would accomplish that goal.</span>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputDiscountCode">Secret Code</label>
    <div class="controls controls-row">
      <input name="submission[discount_code]" type="text" id="inputDiscountCode" class="span4" placeholder="Secret Code (if any)"><span class="span4 inline">If you received a secret code from one of our partners, enter it here!</span>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
       <label class="checkbox">
        <input type="checkbox" id="inputPayment"> If I am accepted to codeStreak, I will pay the <a href="<%= details_path %>#tuition">program tuition</a>
      </label>
      <label class="checkbox">
        <input type="checkbox" id="inputEffort"> If I am accepted to codeStreak, I promise to give it 100% effort and time to succeed
      </label>
      <br />
      <div id="inputStatus" class="alert alert-error" style="display: none">
        Please fill out all fields in the application!
      </div>
      <button type="submit" class="btn btn-primary">Submit Application</button>
    </div>
  </div>
<% end %>

<script>
$(function() {
    $('#submissions_form').submit(function() {
      $(this).ajaxSubmit({
        beforeSubmit: function() {
          hasErrors = false;

          $inputName = $('#inputName');
          if(!$inputName.val()) {
            hasErrors = true;
            $inputName.parents('.control-group').addClass('error');
          } else {
            $inputName.parents('.control-group').removeClass('error');
          }

          $inputEmail = $('#inputEmail');
          if(!$inputEmail.val()) {
            hasErrors = true;
            $inputEmail.parents('.control-group').addClass('error');
          } else {
            $inputEmail.parents('.control-group').removeClass('error');
          }

          $inputEssaySelf = $('#inputEssaySelf');
          if(!$inputEssaySelf.val()) {
            hasErrors = true;
            $inputEssaySelf.parents('.control-group').addClass('error');
          } else {
            $inputEssaySelf.parents('.control-group').removeClass('error');
          }

          $inputEssayTreehouse = $('#inputEssayTreehouse');
          if(!$inputEssayTreehouse.val()) {
            hasErrors = true;
            $inputEssayTreehouse.parents('.control-group').addClass('error');
          } else {
            $inputEssayTreehouse.parents('.control-group').removeClass('error');
          }

          $inputPayment = $('#inputPayment');
          if($inputPayment.is(':checked')) {
            $inputPayment.parent().removeClass('text-error');
          } else {
            hasErrors = true;
            $inputPayment.parent().addClass('text-error');
          }

          $inputEffort = $('#inputEffort');
          if($inputEffort.is(':checked')) {
            $inputEffort.parent().removeClass('text-error');
          } else {
            hasErrors = true;
            $inputEffort.parent().addClass('text-error');
          }

          if (hasErrors) {
            $('#inputStatus').show();
            $('#inputStatus').addClass('alert-error');
            return false;
          } else {
            $('form input').attr('disabled', 'disabled');
            $('form textarea').attr('disabled', 'disabled');
            $('form button').attr('disabled', 'disabled');
            $('#inputStatus').removeClass('alert-error');
            $('#inputStatus').html('Submitting, one moment...');
          }
        },
        success: function() {
          $('form button').hide();
          $('#inputStatus').text("Thanks for submitting your application. We'll review it and get back to you soon!");
          $('#inputStatus').removeClass('alert-error');
          $('#inputStatus').addClass('alert-success');
          $('#inputStatus').append('<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/998027554/?value=0&amp;label=w48mCI724gMQouLy2wM&amp;guid=ON&amp;script=0"/>');
          $('#inputStatus').show();
        },
        error: function() {
          $('#inputStatus').text("Something went wrong - please email contact@codestreak.com and we'll fix the issue!");
          $('#inputStatus').addClass('alert-error');
          $('#inputStatus').removeClass('alert-success');
          $('#inputStatus').show();
        }
      });
      return false;
    });
});
</script>